name: Build Android
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install hscript --quiet
          haxelib install hxcpp --quiet
          haxelib git faxe https://github.com/uhwot/faxe
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git extension-androidtools https://github.com/M.A.J.W.A.D/extension-androidtools.git
          haxelib git linc_luajit https://github.com/SiroxDev/linc_luajit.git

      - name: Configure Android
        run: |
          haxelib run lime setup android --no-install
          echo "y" | haxelib run lime setup android
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle

      - name: Build APK
        run: haxelib run lime build android -release
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PsychEngine-Android
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
