name: Build Android
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib install flixel-ui 2.4.0
          haxelib install flixel-addons 2.11.0
          haxelib install hscript
          haxelib install hxcpp
          haxelib git faxe https://github.com/uhwot/faxe
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git extension-androidtools https://github.com/M.A.J.W.A.D/extension-androidtools.git
          haxelib git linc_luajit https://github.com/SiroxDev/linc_luajit.git

      - name: Configure Lime
        run: |
          haxelib run lime setup
          haxelib run lime setup android --no-install
          # Esto le dice a Lime dónde está el SDK y NDK que GitHub ya trae preinstalados
          echo "y" | haxelib run lime setup android
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle

      - name: Build APK
        run: haxelib run lime build android -release
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PsychEngine-Android
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
